type: sim_puppeteer
name: sim_puppeteer_g1

teleop_dt: 0.02
output_type: joint_pos # 'joint_pos' or 'delta_eef_pose'

# for eef-based mapping
motion_mapping: direct_scaling # 'direct_scaling', 'follower_reprojection', 'leader_reprojection'
motion_scale: 1.0

limb_joint_names:
  left_leg:
    - 'left_hip_pitch_joint'
    - 'left_hip_roll_joint'
    - 'left_hip_yaw_joint'
    - 'left_knee_joint'
  right_leg:
    - 'right_hip_pitch_joint'
    - 'right_hip_roll_joint'
    - 'right_hip_yaw_joint'
    - 'right_knee_joint'
  left_arm:
    - 'left_shoulder_pitch_joint'
    - 'left_shoulder_roll_joint'
    - 'left_shoulder_yaw_joint'
    - 'left_elbow_joint'
    - 'left_wrist_roll_joint'
    - 'left_wrist_pitch_joint'
    - 'left_wrist_yaw_joint'
  right_arm:
    - 'right_shoulder_pitch_joint'
    - 'right_shoulder_roll_joint'
    - 'right_shoulder_yaw_joint'
    - 'right_elbow_joint'
    - 'right_wrist_roll_joint'
    - 'right_wrist_pitch_joint'
    - 'right_wrist_yaw_joint'

end_effector_link: #
  left_leg: 'left_ankle_link'
  right_leg: 'right_ankle_link'
  left_arm: 'left_end_effector_link'
  right_arm: 'right_end_effector_link'

hand_joint_names:
  left_leg: []
  right_leg: []
  left_arm: ['left/gripper']
  right_arm: ['right/gripper']

hand_limits: # for gripper range mapping
  left_arm: [[0.0, 1.0]]
  right_arm: [[0.0, 1.0]]
  left_leg: []
  right_leg: []



init_qpos: [0.0, 0.0, 0.0, 0.0,
            0.0, 0.0, 0.0, 0.0,
            0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
            0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

# leader limb -> follower limb
direct_mapping: [] # default is empty, which means 1:1 mapping

asset_cfg:
  asset_dir: 'models/'
  urdf_path: 'models/leaders/g1_baby.urdf'
  xml_path: 'models/leaders/g1_baby.urdf'

direct_mapping_available_robots: ['g1']

render_base: 'mujoco'
viewer_args:
    trimesh:
      pq: [-0.84400246, -0.74844073,  0.63149086,  0.79797548,  0.49961321, -0.17853849, -0.28591218]