type: puppeteer
name: puppeteer_omy

teleop_dt: 0.02
output_type: joint_pos # 'joint_pos' or 'delta_eef_pose'

# for eef-based mapping
motion_mapping: direct_scaling
motion_scale: 1.0

# for ROS-based controller
leader_subscribe_topic: '/leaders/joint_states'
limb_joint_names:
  robot1: ['joint1', 'joint2', 'joint3', 'joint4', 'joint5', 'joint6']

end_effector_link:
  robot1: 'end_effector_link'

hand_joint_names:
  robot1: ['gripper']

init_qpos: [0.0, -1.0, 1.945, -0.4, 1.571, -0.12, 0.0]

# leader limb -> follower limb
direct_mapping: # default is empty, which means 1:1 mapping
  robot1: 'robot1'


reset_pose: [[-0.153, -0.016, 0.374]]
reset_cube: [0.200, 0.100, 0.050]

asset_cfg:
  asset_dir: 'models/'
  urdf_path: 'models/open_manipulator_y/open_manipulator_y_leader.urdf'
  xml_path: 'models/open_manipulator_y/open_manipulator_y_leader.urdf'

direct_mapping_available_robots: ['omy']
hand_limits: # for gripper range mapping
  robot1: [[0.0, -1.0]] #[-0.39, 0.56]

render_base: 'trimesh'
viewer_args:
    trimesh:
      pq: [1.51597506, 1.04149913, 0.88220541, 0.34222756, 0.24566453, 0.50989899, 0.75002151]